# Configuration File
#

# Information for compile
exclude: ["Gemfile", "README.md"]

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
baseurl: ""

collections:
  news:
    output: true
    permalink: /news/:title/

# the base hostname & protocol for your site
url: "http://localhost:4000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layout: "archive"
  permalinks:
    category: "/category/:name/"

#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################

# This is your site title
title: Dynamics of Neural Systems Laboratory
lang: en-US
header-title: <strong>D</strong>ynamics <br> <strong>O</strong>f <br> <strong>N</strong>eural <br> <strong>S</strong>ystems <br> Laboratory
header-tagline: Medical University of Vienna

####################################
######   CTA Header Buttons   ######
####################################
#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: your_email@example.com

####################################
######  Global Social Links   ######
####################################
twitter: "https://twitter.com/AGosztolai"
scholar: "https://scholar.google.com/citations?user=fVGCjMsAAAAJ&hl=en"

#########################
######   Widgets   ######
#########################

# Google Map JS api
key-api: YOUR_GOOGLE_MAP_API_KEY
map-text: Sera Google Map
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

# show future posts
future: true

#####################################
#############   About   #############
#####################################
about-title: Our Mission
about-description: |
  Our brains and AI systems solve computational challenges in a distributed manner, across neurons and 
  across brain areas, encoded in the collective activity of neural populations. Our research seeks to 
  understand the dynamical processes underpinning neural computations to derive algorithmic principles 
  shared by these fundamentally different systems. We believe that understanding how the brain orchestrates
  the dynamics of its neurons to perform complex computations will lead to a deeper understanding of 
  intelligence and behaviour. 
  <br><br>
  We are motivated by two synergistic aims:
  <br><br>
  1. Developing novel methods using theoretical machine learning, geometry and dynamical systems theory 
  for discovering better models of how the brain works.
  <br>
  2. Reverse-engineering the dynamical systems that underpin cognitive processes to develop more advanced 
  AI systems that benefit clinical applications such as brain-machine interfaces.

#####################################
############  Research  #############
#####################################
portfolio-title: Selected research

portfolio-categories:
  [dynamical systems, geometry, machine learning, computational neuroscience]

portfolio:
  # Portfolio Item
  - title: Interpretable representation of neural dynamics using unsupervised geometric deep learning
    categories: [dynamical systems, geometry, machine learning, computational neuroscience]
    journal: under review
    image: MARBLE.jpg
    url: "https://www.researchsquare.com/article/rs-2882348/v1"

  # Portfolio Item
  - title: Estimating three-dimensional animal poses using a single camera
    categories: [machine learning, computational neuroscience]
    journal: Nature Methods, 2021
    image: LiftPose3D.jpg
    url: "https://www.nature.com/articles/s41592-021-01226-z"

  # Portfolio Item
  - title: Geometric connection between the dynamics over networks and connectivity
    categories: [dynamical systems, geometry]
    journal: Nature Communications, 2021
    image: ORcurvature.jpg
    url: "https://www.nature.com/articles/s41467-021-24884-1"
    

#####################################
############### Team ################
#####################################
team-title: Team
team-description: 

  We are a melting pot of researchers from diverse backgrounds, including physics, mathematics, computer science, 
  and neuroscience. We are united by our drive for understanding the dynamics of neural systems and their 
  implications for both biological and artificial intelligence. If this resonates with you,
  we encourage you to reach out to us. 

  <br><br>

  We are always on the lookout for talented Master's students from universities in Austria or abroad. Please get 
  in touch with Adam Gosztolai if you are interested in joining our lab for your thesis project. 
  
  <br><br>

  While we are currently not advertising any open PhD or Postdoctoral positions, we are open to
  exceptional candidates who are passionate about our research areas. If you believe you would be a great
  fit for our team, please do not hesitate to reach out to Adam Gosztolai with your CV and a motivation letter 
  describing why you would like to join our lab and what you can contribute to our research. Postdoctoral
  candidates are encouraged to apply for competitive fellowships (e.g., EMBO, Marie Curie, etc.).

  # In addition, we also have Postdoctoral, PhD and internships (e.g., master's thesis projects) available in the 
  # topic of foundation models for understanding the neural control of locomotion in macaques. See this 
  # <a href="https://forms.gle/RNpCPQ7bBVJD9oMv7">link</a> for more details.

#
# Team Members
#
team:
  # Team Member
  - name: Adam Gosztolai
    tagline: Principal Investigator
    avatar: adam.jpg
    linkname: adamgosztolai
    email: "adam.gosztolai@meduniwien.ac.at"
    twitter: "https://twitter.com/AGosztolai"
    scholar: "https://scholar.google.com/citations?user=fVGCjMsAAAAJ&hl=en"
    github: "https://github.com/Dynamics-of-Neural-Systems-Lab"

  # Team Member
  - name: Bálint Király
    tagline: Postdoctoral Researcher <br> BSc/MSc Physics <br> PhD Neuroscience 
    avatar: balint.jpg
    email: "mailto:balint.kiraly@meduniwien.ac.at"
    scholar: "https://www.researchgate.net/profile/Balint-Kiraly"

  - name: Clara Grotehans
    tagline: PhD Student <br> BSc/MSc Machine Learning
    avatar: clara.jpg
    email: "mailto:clara.grotehans@meduniwien.ac.at"

  - name: Dennis Duncan
    tagline: PhD Student <br> BSc/MSc Physics
    avatar: dennis.jpg
    email: "mailto:dennis.duncan@meduniwien.ac.at"
    scholar: "https://scholar.google.com/citations?user=F4ifo24AAAAJ&hl=en"

  - name: James Ferguson
    tagline: Academic visitor <br> PhD Mathematics
    avatar: james.jpeg

  - name: Jan Leszczyk
    tagline: Master's Student <br> BSc Computer Science
    avatar: jan.jpg

  - name: Jiaming Qian
    tagline: starting Jan 2026, MSc Bioengineering
    avatar: jiaming.jpg

  - name: Divyansh Gupta
    tagline: starting Jan 2026, BTech/MTech Computer Science, PhD Systems Neuroscience
    avatar: divyansh.jpg

team-alumni-title: Alumni
alumni: 
  - name: Jakob Lembacher (Medical student, Diplomarbeit, "Pose estimation in macaques")
  - name: Robert Peach (Postdoctoral researcher, currently Principal Investigator at University of Würzburg)
  - name: Albert López i Serrano (Research intern, "Koopman operator theory for data-driven dynamical systems")
  - name: Iolo Jones (Research intern, "Geometry regularised generative flow matching models")
  - name: Jacob Bamberger (Research intern, "Geometry regularised generative flow matching models")

funding-title: Funding sources
